on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - name: Mount bazelisk cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazelisk"
          key: bazelisk
      - name: Install bazelisk
        run: |
          set -eo pipefail
          BIN=/home/runner/.cache/bazelisk/bazelisk-linux-amd64
          [[ -f "$BIN" ]] || curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.12.0/bazelisk-linux-amd64" > "$BIN"
          echo "6b0bcb2ea15bca16fffabe6fda75803440375354c085480fe361d2cbf32501db $BIN" | sha256sum -c 
          sudo chmod +x "$BIN"
          sudo ln -s "$BIN" /usr/bin/bazel
      - name: Test
        run: |
          test/test.sh
